/**
 * Real-data adapter: loads the preprocessed per-user JSON files and returns
 * data in the shape the existing app expects (DNAMatch[]).
 *
 * Source: `public/data/user-{id}.json` — generated by
 * `scripts/preprocess_pickle.py` from the 254K-pair real dataset.
 *
 * The JSON shape:
 *   {
 *     user: { id, displayName, initials, avatarColor, primaryPopulation,
 *             ancestryProfile, surnamePool },
 *     matchCount: number,
 *     matches: DNAMatch[]
 *   }
 */

import { DNAMatch, AncestryComponent } from '@/data/types';

export interface DemoUser {
  id: string;            // 'user-1' .. 'user-10'
  displayName: string;
  initials: string;
  avatarColor: string;
  primaryPopulation: string;
  ancestryProfile: AncestryComponent[];
  surnamePool: string[];
  matchCount: number;
}

export interface UserDataset {
  user: DemoUser;
  matches: DNAMatch[];
}

interface IndexEntry {
  id: string;
  displayName: string;
  initials: string;
  avatarColor: string;
  primaryPopulation: string;
  matchCount: number;
}

interface IndexFile {
  users: IndexEntry[];
}

let _indexCache: IndexEntry[] | null = null;
const _userCache: Record<string, UserDataset> = {};

/**
 * Load the lightweight index of all 10 demo users (for the dropdown selector).
 */
export async function loadUserIndex(): Promise<IndexEntry[]> {
  if (_indexCache) return _indexCache;
  const res = await fetch('/data/index.json');
  if (!res.ok) throw new Error(`Failed to load user index: ${res.status}`);
  const data: IndexFile = await res.json();
  _indexCache = data.users;
  return data.users;
}

/**
 * Load a specific user's full dataset (matches + identity).
 * Cached in memory after first fetch.
 */
export async function loadUserDataset(userId: string): Promise<UserDataset> {
  if (_userCache[userId]) return _userCache[userId];

  const res = await fetch(`/data/${userId}.json`);
  if (!res.ok) throw new Error(`Failed to load ${userId}: ${res.status}`);

  const raw = await res.json();
  const dataset: UserDataset = {
    user: {
      id: raw.user.id,
      displayName: raw.user.displayName,
      initials: raw.user.initials,
      avatarColor: raw.user.avatarColor,
      primaryPopulation: raw.user.primaryPopulation,
      ancestryProfile: raw.user.ancestryProfile,
      surnamePool: raw.user.surnamePool,
      matchCount: raw.matchCount,
    },
    matches: raw.matches as DNAMatch[],
  };

  _userCache[userId] = dataset;
  return dataset;
}

/**
 * Read the selected userId from the URL (?user=user-N), defaulting to user-1.
 */
export function getSelectedUserIdFromUrl(): string {
  if (typeof window === 'undefined') return 'user-1';
  const params = new URLSearchParams(window.location.search);
  return params.get('user') || 'user-1';
}

/**
 * Set the selected userId in the URL without a full reload.
 */
export function setSelectedUserIdInUrl(userId: string): void {
  if (typeof window === 'undefined') return;
  const url = new URL(window.location.href);
  url.searchParams.set('user', userId);
  window.history.replaceState({}, '', url.toString());
}
